<?php

namespace App\Model;


use App\Entity\Article;

/**
 * Class ArticleController
 * @package blog\src\Model
 */
class ArticleModel extends AbstractModel
{
    protected string $tableName = 'article';

    protected string $className = Article::class;

    public function findAll(): array
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }

    public function findOne($id): array
    {
        return parent::findOne($id); // TODO: Change the autogenerated stub
    }

}



